apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: zaidi6269/backend-app
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
          ports:
            - containerPort: 80
